owner: activatedgeek
repo: status

sites:
  - name: Website
    url: https://sanyamkapoor.com
  - name: CV
    url: https://sanyamkapoor.com/cv
  - name: Wine Map
    url: https://maps.sanyamkapoor.com/wine

status-website:
  cname: status.sanyamkapoor.com
  logoUrl: https://sanyamkapoor.com/sk.svg
  faviconSvg: https://sanyamkapoor.com/favicon.svg
  name: sanyamkapoor.com Status
  introTitle: "Status by **Upptime**."
  navbar:
    - title: sanyamkapoor.com Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: gh-upptime
